services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: pft-backend
    container_name: pft-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: profiltech-app-webserver
    restart: unless-stopped
    ports:
      - "${APP_PORT}"

    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:latest
    container_name: profiltech-app-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pftdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  pftdata:
    driver: local
